### ISSUE TITLE
Performance spike fix

### ISSUE THREAD

**Issue by haywirephoenix** [wacki/Unity-VRInputModule#12]
Add LaserPointerInputModule.cs:56

`UICamera.cullingMask = LayerMask.NameToLayer("UI");
UICamera.stereoTargetEye = StereoTargetEyeMask.None;`

**Comment by paulhayes** [comment]
Yes, makes sense.

Can you modify the file directly on github and create a pull request.

**Comment by haywirephoenix** [comment]
Okay, I've got an input upgrade for you aswell that works with the new api

**Comment by haywirephoenix** [comment]
fix #13
